### PR TITLE
chore: Update Gradle to 8.2 and AGP to 8.2.0

### PR DESCRIPTION
**Pull request by thearaks**
Please accept this pull request and release a new version of the library since it's blocking compilation with Flutter 3.16.
Thank you!

### CODE REVIEW

**Comment by daadu** [comment]
The changes seems correct. Some issue in the CI - Let me try and fix it.

**Comment by daadu** [comment]
@thearaks Please merge https://github.com/CodeAtlas/WiFiFlutter/pull/1

**Comment by thearaks** [comment]
@daadu done, you can approve the workflow now 😉

**Comment by daadu** [comment]
@thearaks another PR - https://github.com/CodeAtlas/WiFiFlutter/pull/2

This should fix everything.

**Comment by daadu** [comment]
Thanks for the PR.

**Comment by daadu** [comment]
This change has landed in pub.dev with both packages.

@thearaks Thanks for the contribution, you can check yourself [here](https://github.com/flutternetwork/WiFiFlutter/blob/master/CONTRIBUTORS.md)!!

**Pull request merged**
