### PR TITLE
feat(wifi_iot): Allows to change the default connection timeout from the application

### LINKED ISSUE #304: Connection timeout cannot be overridden
When connecting to wifi programmatically, if the password is incorrect, a system window appears with a suggestion to enter the password. This is given only 30 seconds, including the connection time. That is, there are only about 15 seconds left to enter the password. This patch allows you to override the default timeout specified in the java code as a constant https://github.com/flutternetwork/WiFiFlutter/blob/4fe564b707b5b1b8bacea0af78bd9cc7c624c8ca/packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java#L1396
[timeout-connection.txt](https://github.com/flutternetwork/WiFiFlutter/files/9439277/timeout-connection.txt)

Format files .patch cannot be attached, so I attach a txt, please convert it to a patch, in case you add a change to the plugin code.

### PR DESCRIPTION
**Pull request by adnreych**
Closes #304

### CODE REVIEW

**Comment by daadu** [comment]
Can also be done for iOS?

**Comment by daadu** [comment]
> Can also be done for iOS?

Looks like not needed in iOS.

**Comment by adnreych** [comment]
I haven't tested it on iOS, so it's up to you.
I have never written a code for swift, moreover, I don’t know how the connection to the wifi happens on iOS, so I didn’t make changes in that part.

**Review by daadu — APPROVED** [review]
@adnreych  Did some changes
 - formatting
 - added `timeoutInSeconds` to `findAndConnect`

Rest looks good to me.

**Comment by daadu** [comment]
This feature has landed on pub.dev with [v0.3.17](https://pub.dev/packages/wifi_iot/versions/0.3.17).

@adnreych Thanks for your contribution. Check yourself [here](https://github.com/flutternetwork/WiFiFlutter/blob/master/CONTRIBUTORS.md)!

**Pull request merged**
