### PR TITLE
fix: android asking user permission every time

### PR DESCRIPTION
**Pull request by fernando-s97**
I've add the bssid when connecting to a network, because in my case, Android kept showing a dialog asking if I really wanted to connect to the network. After adding the BSSID, android only asks the first time.

I've tested this on Android 11 with the following code:

```dart
WiFiForIoTPlugin.connect(
  ssid,
  password: password,
  security: NetworkSecurity.WPA,
  joinOnce: false,
);
```

### CODE REVIEW

**Comment by daadu** [comment]
This looks like incorrect implmentation of what you want. Scanning inside `connectTo` would require location permission  and location to be enabled.

The correct solution to fix this would be to let user pass `bssid` as an arg to `connect` and handling it on both android and ios side.

I did not check you previous PR at #158 properly (beacuse of lot of white space changes!). Did it implement what I mentioned above?

**Comment by fernando-s97** [comment]
The code is counter intuitive, but it doesn't perform any scan. The `moWifi.getScanResults()` just get the lastest scan results (without performing any scan) and if the ssid in question is available there, we pass the bssid while connecting.

I haven't thouched the #158 because I didn't want to add docs to the code and to the README knowing that wifi_iot will become legacy. And I was out of time :/

**Comment by daadu** [comment]
@fernando-s97 Can you make sure that this does not require additional permission or location to be enabled (if required then fails silently)?

**Comment by fernando-s97** [comment]
image

Would this be a problem?

**Comment by fernando-s97** [comment]
I do think so. What should I do in this case?

1. Only use the bssid if `ACCESS_FINE_LOCATION` is granted
2. Handle permission request
3. Don't try to find the at all (if that's the case, I would have close this issue and work on #158)

**Comment by daadu** [comment]
Ideally, we will should to add `bssid` option to connect. But this is a good idea to figure `bssid` from "scanned results" to avoid frequent approval - but should not require any permission or other additional requirement.

**Comment by fernando-s97** [comment]
I don't think there is any way to figure the bssid besides the way I did, so no way to do this without requiring any permission or other additional requirement.

I'll try to wornk on the #158 then.

**Comment by daadu** [comment]
> .. so no way to do this without requiring any permission or other additional requirement.

What I meant was no "additional" permission or requirement that is already required by `connectTo` method

**Comment by fernando-s97** [comment]
I got it, but as per what I've seen, the `connectTo` doesn't require any specific permission. Did I miss something?

If I'm correct, this correction indeed won't work by default, with the current implementation.

**Comment by daadu** [comment]
@fernando-s97 Firstly, sorry for not being active on it. I have been thinking about this feature - and it looks like this shouldn't be done this way - deriving mac/bssid from scanned results - what if there are two networks with same ssid? This could lead to connecting to wrong network being connected. Therefore this should be kept in user-space.

I think we should work on this problem - not asking user for permission to connect every time - but should not be done in such opaque way.

There are 2 alternative to this:
1. User handles everything - connects to a network with ssid - after connected - gets the bssid of current network and caches it - next time connects with that.
2. Implicitly doing the above - but will have to "cache" the bssid in persistent storage - so that it works after app restarts (or not could only just use it for current app session) - also give user to disable this behaviour with a flag in `connect` method, like `bool useCachedBSSID=true`

In option 1 - only thing required from our end is to put this pattern in README. Therefore I prefer this.

@fernando-s97  Let me know your views on this.

**Comment by daadu** [comment]
@fernando-s97 Closing this, as mentioned above because of the wrong approach - opened new issue regarding it at #282 - feel free to discuss there and work on it.

**Pull request closed without merging**
